# Site settings
title: Oberheim's Blog
email: alexander.heimonen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alexander Heimonen is a .NET Consultant at Ciber Sweden AB and maintains this programming blog on his free time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oberheim.github.io" # the base hostname & protocol for your site
twitter_username: Oberheimz
github_username:  Oberheim

# Build settings
markdown: kramdown
highlighter: pygments
